services:
  db:
    container_name: mes_db
    image: postgres:latest
    command: -c 'max_connections=200'
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    container_name: test_mes_db
    image: postgres
    command: -c 'max_connections=200'
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mesdb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5

  backend:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash ./start.sh
    volumes:
      - ./:/app

volumes:
  pgdata: